[package]
name = "Waterfall"
version = "0.1.0"
edition = "2021"

[dependencies]
curl = "0.4.47"
libc = "0.2.169"
serde_json = "1.0.140"
winapi = { version = "0.3", features = ["winsock2", "ws2def", "ws2ipdef", "ws2tcpip"] }

[[bin]]

name = "waterfall"
path = "main.rs"
